/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function n(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var q=ba(this);function t(a,b){if(b)a:{var c=q;a=a.split(".");for(var e=0;e<a.length-1;e++){var h=a[e];if(!(h in c))break a;c=c[h]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}}
function v(){this.g=!1;this.b=null;this.j=void 0;this.a=1;this.m=this.f=0;this.c=null}function w(a){if(a.g)throw new TypeError("Generator is already running");a.g=!0}v.prototype.l=function(a){this.j=a};function x(a,b){a.c={G:b,J:!0};a.a=a.f||a.m}v.prototype.return=function(a){this.c={return:a};this.a=this.m};function y(a,b,c){a.a=c;return{value:b}}function ca(a){a.a=0;a.f=0}function da(a){a.f=0;var b=a.c.G;a.c=null;return b}function ea(a){this.a=new v;this.b=a}
function fa(a,b){w(a.a);var c=a.a.b;if(c)return z(a,"return"in c?c["return"]:function(e){return{value:e,done:!0}},b,a.a.return);a.a.return(b);return B(a)}function z(a,b,c,e){try{var h=b.call(a.a.b,c);if(!(h instanceof Object))throw new TypeError("Iterator result "+h+" is not an object");if(!h.done)return a.a.g=!1,h;var l=h.value}catch(f){return a.a.b=null,x(a.a,f),B(a)}a.a.b=null;e.call(a.a,l);return B(a)}
function B(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.g=!1,{value:b.value,done:!1}}catch(c){a.a.j=void 0,x(a.a,c)}a.a.g=!1;if(a.a.c){b=a.a.c;a.a.c=null;if(b.J)throw b.G;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ha(a){this.next=function(b){w(a.a);a.a.b?b=z(a,a.a.b.next,b,a.a.l):(a.a.l(b),b=B(a));return b};this.throw=function(b){w(a.a);a.a.b?b=z(a,a.a.b["throw"],b,a.a.l):(x(a.a,b),b=B(a));return b};this.return=function(b){return fa(a,b)};this[Symbol.iterator]=function(){return this}}function ia(a){function b(e){return a.next(e)}function c(e){return a.throw(e)}return new Promise(function(e,h){function l(f){f.done?e(f.value):Promise.resolve(f.value).then(b,c).then(l,h)}l(a.next())})}
function C(a){return ia(new ha(new ea(a)))}t("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(h||"")+"_"+e++,h)}function c(h,l){this.a=h;p(this,"description",{configurable:!0,writable:!0,value:l})}if(a)return a;c.prototype.toString=function(){return this.a};var e=0;return b});
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var e=q[b[c]];"function"===typeof e&&"function"!=typeof e.prototype[a]&&p(e.prototype,a,{configurable:!0,writable:!0,value:function(){return ja(aa(this))}})}return a});function ja(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
t("Promise",function(a){function b(f){this.b=0;this.c=void 0;this.a=[];this.l=!1;var d=this.f();try{f(d.resolve,d.reject)}catch(g){d.reject(g)}}function c(){this.a=null}function e(f){return f instanceof b?f:new b(function(d){d(f)})}if(a)return a;c.prototype.b=function(f){if(null==this.a){this.a=[];var d=this;this.c(function(){d.g()})}this.a.push(f)};var h=q.setTimeout;c.prototype.c=function(f){h(f,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var f=this.a;this.a=[];for(var d=0;d<f.length;++d){var g=
f[d];f[d]=null;try{g()}catch(k){this.f(k)}}}this.a=null};c.prototype.f=function(f){this.c(function(){throw f;})};b.prototype.f=function(){function f(k){return function(m){g||(g=!0,k.call(d,m))}}var d=this,g=!1;return{resolve:f(this.D),reject:f(this.g)}};b.prototype.D=function(f){if(f===this)this.g(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.M(f);else{a:switch(typeof f){case "object":var d=null!=f;break a;case "function":d=!0;break a;default:d=!1}d?this.C(f):this.j(f)}};
b.prototype.C=function(f){var d=void 0;try{d=f.then}catch(g){this.g(g);return}"function"==typeof d?this.I(d,f):this.j(f)};b.prototype.g=function(f){this.m(2,f)};b.prototype.j=function(f){this.m(1,f)};b.prototype.m=function(f,d){if(0!=this.b)throw Error("Cannot settle("+f+", "+d+"): Promise already settled in state"+this.b);this.b=f;this.c=d;2===this.b&&this.L();this.v()};b.prototype.L=function(){var f=this;h(function(){if(f.A()){var d=q.console;"undefined"!==typeof d&&d.error(f.c)}},1)};b.prototype.A=
function(){if(this.l)return!1;var f=q.CustomEvent,d=q.Event,g=q.dispatchEvent;if("undefined"===typeof g)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):"function"===typeof d?f=new d("unhandledrejection",{cancelable:!0}):(f=q.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.c;return g(f)};b.prototype.v=function(){if(null!=this.a){for(var f=0;f<this.a.length;++f)l.b(this.a[f]);this.a=null}};var l=new c;b.prototype.M=
function(f){var d=this.f();f.B(d.resolve,d.reject)};b.prototype.I=function(f,d){var g=this.f();try{f.call(d,g.resolve,g.reject)}catch(k){g.reject(k)}};b.prototype.then=function(f,d){function g(u,A){return"function"==typeof u?function(X){try{k(u(X))}catch(Y){m(Y)}}:A}var k,m,r=new b(function(u,A){k=u;m=A});this.B(g(f,k),g(d,m));return r};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.B=function(f,d){function g(){switch(k.b){case 1:f(k.c);break;case 2:d(k.c);break;default:throw Error("Unexpected state: "+
k.b);}}var k=this;null==this.a?l.b(g):this.a.push(g);this.l=!0};b.resolve=e;b.reject=function(f){return new b(function(d,g){g(f)})};b.race=function(f){return new b(function(d,g){for(var k=n(f),m=k.next();!m.done;m=k.next())e(m.value).B(d,g)})};b.all=function(f){var d=n(f),g=d.next();return g.done?e([]):new b(function(k,m){function r(X){return function(Y){u[X]=Y;A--;0==A&&k(u)}}var u=[],A=0;do u.push(void 0),A++,e(g.value).B(r(u.length-1),m),g=d.next();while(!g.done)})};return b});
function D(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}t("String.prototype.repeat",function(a){return a?a:function(b){var c=D(this,null,"repeat");if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var e="";b;)if(b&1&&(e+=c),b>>>=1)c+=c;return e}});
t("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});t("Array.prototype.includes",function(a){return a?a:function(b,c){var e=this;e instanceof String&&(e=String(e));var h=e.length;c=c||0;for(0>c&&(c=Math.max(c+h,0));c<h;c++){var l=e[c];if(l===b||Object.is(l,b))return!0}return!1}});t("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==D(this,b,"includes").indexOf(b,c||0)}});
t("String.prototype.startsWith",function(a){return a?a:function(b,c){var e=D(this,b,"startsWith"),h=e.length,l=b.length;c=Math.max(0,Math.min(c|0,e.length));for(var f=0;f<l&&c<h;)if(e[c++]!=b[f++])return!1;return f>=l}});function E(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
t("WeakMap",function(a){function b(g){this.a=(d+=Math.random()+1).toString();if(g){g=n(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}}function c(){}function e(g){var k=typeof g;return"object"===k&&null!==g||"function"===k}function h(g){if(!E(g,f)){var k=new c;p(g,f,{value:k})}}function l(g){var k=Object[g];k&&(Object[g]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&h(m);return k(m)})}if(function(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),k=Object.seal({}),
m=new a([[g,2],[k,3]]);if(2!=m.get(g)||3!=m.get(k))return!1;m.delete(g);m.set(k,4);return!m.has(g)&&4==m.get(k)}catch(r){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();l("freeze");l("preventExtensions");l("seal");var d=0;b.prototype.set=function(g,k){if(!e(g))throw Error("Invalid WeakMap key");h(g);if(!E(g,f))throw Error("WeakMap key fail: "+g);g[f][this.a]=k;return this};b.prototype.get=function(g){return e(g)&&E(g,f)?g[f][this.a]:void 0};b.prototype.has=function(g){return e(g)&&E(g,
f)&&E(g[f],this.a)};b.prototype.delete=function(g){return e(g)&&E(g,f)&&E(g[f],this.a)?delete g[f][this.a]:!1};return b});
t("Map",function(a){function b(){var d={};return d.o=d.next=d.head=d}function c(d,g){var k=d.a;return ja(function(){if(k){for(;k.head!=d.a;)k=k.o;for(;k.next!=k.head;)return k=k.next,{done:!1,value:g(k)};k=null}return{done:!0,value:void 0}})}function e(d,g){var k=g&&typeof g;"object"==k||"function"==k?l.has(g)?k=l.get(g):(k=""+ ++f,l.set(g,k)):k="p_"+g;var m=d.b[k];if(m&&E(d.b,k))for(d=0;d<m.length;d++){var r=m[d];if(g!==g&&r.key!==r.key||g===r.key)return{id:k,list:m,index:d,h:r}}return{id:k,list:m,
index:-1,h:void 0}}function h(d){this.b={};this.a=b();this.size=0;if(d){d=n(d);for(var g;!(g=d.next()).done;)g=g.value,this.set(g[0],g[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var d=Object.seal({x:4}),g=new a(n([[d,"s"]]));if("s"!=g.get(d)||1!=g.size||g.get({x:4})||g.set({x:4},"t")!=g||2!=g.size)return!1;var k=g.entries(),m=k.next();if(m.done||m.value[0]!=d||"s"!=m.value[1])return!1;m=k.next();return m.done||4!=m.value[0].x||
"t"!=m.value[1]||!k.next().done?!1:!0}catch(r){return!1}}())return a;var l=new WeakMap;h.prototype.set=function(d,g){d=0===d?0:d;var k=e(this,d);k.list||(k.list=this.b[k.id]=[]);k.h?k.h.value=g:(k.h={next:this.a,o:this.a.o,head:this.a,key:d,value:g},k.list.push(k.h),this.a.o.next=k.h,this.a.o=k.h,this.size++);return this};h.prototype.delete=function(d){d=e(this,d);return d.h&&d.list?(d.list.splice(d.index,1),d.list.length||delete this.b[d.id],d.h.o.next=d.h.next,d.h.next.o=d.h.o,d.h.head=null,this.size--,
!0):!1};h.prototype.clear=function(){this.b={};this.a=this.a.o=b();this.size=0};h.prototype.has=function(d){return!!e(this,d).h};h.prototype.get=function(d){return(d=e(this,d).h)&&d.value};h.prototype.entries=function(){return c(this,function(d){return[d.key,d.value]})};h.prototype.keys=function(){return c(this,function(d){return d.key})};h.prototype.values=function(){return c(this,function(d){return d.value})};h.prototype.forEach=function(d,g){for(var k=this.entries(),m;!(m=k.next()).done;)m=m.value,
d.call(g,m[1],m[0],this)};h.prototype[Symbol.iterator]=h.prototype.entries;var f=0;return h});function ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var e=c.slice();e.push.apply(e,arguments);return a.apply(this,e)}};function F(a){return(void 0===a?1:a)*G.j}function la(a){var b=G;return Math.max(1,(void 0===a?1:a)*(b.A?Math.floor(b.c/100*b.C):b.c))}
function ma(){var a=G;window.firebase.firestore().collection("configuration").orderBy("timestamp","desc").limit(1).onSnapshot(function(b){if(0<b.size){b=b.docs[0].data();a.m=b.hasOwnProperty("enabled")?b.enabled:a.m;a.v=b.hasOwnProperty("event_start")?b.event_start:a.v;a.f=b.hasOwnProperty("fallback_url")?b.fallback_url:a.f;a.j=b.hasOwnProperty("config")?b.callback_window_ms:a.j;a.c=b.hasOwnProperty("callback_threshold")?b.callback_threshold:a.c;a.A=b.hasOwnProperty("threshold_is_percentage")?b.threshold_is_percentage:
a.A;a.g=b.hasOwnProperty("admin_users")?b.admin_users:a.g;a.b=b.hasOwnProperty("youtube_video")?b.youtube_video:a.b;a.a=b.hasOwnProperty("youtube_chat")?b.youtube_chat:a.a;b=n(a.l);for(var c=b.next();!c.done;c=b.next())c=c.value,c(a)}},function(b){console.error("Error querying Firestore: ",b)});window.firebase.firestore().collection("_user_presence").where("sessions",">",{}).onSnapshot(function(b){if(0<b.size){a.C=b.docs.length;b=n(a.l);for(var c=b.next();!c.done;c=b.next())c=c.value,c(a)}},function(b){console.error("Error querying Firestore: ",
b)})}var G=new function(){this.m=!1;this.v=null;this.D=!1;this.f="";this.j=1E4;this.c=3;this.A=!1;this.C=0;this.a=this.b="";this.g=[];this.l=[]};function na(a,b,c){c=c||oa;for(var e=0,h=a.length,l;e<h;){var f=e+(h-e>>>1);var d=c(b,a[f]);0<d?e=f+1:(h=f,l=!d)}return l?e:-e-1}function oa(a,b){return a>b?1:a<b?-1:0};function pa(){this.text="callback-message-";this.index=0}pa.prototype.next=function(){return this.text+this.index++};function qa(a){try{var b=new URL(a);/(.*\.)?googleusercontent\.com$/.test(b.hostname)&&b.searchParams.set("sz","150");return b.toString()}catch(c){if(c instanceof TypeError)return a;throw c;}}
function ra(a){var b=H().querySelectorAll(".message-container");if(0===b.length)return null;a=na(b,a,function(c,e){var h=parseInt(e.getAttribute("timestamp"),10);if(!h)throw Error("Child "+e.id+" has no 'timestamp' attribute");return c-h});return a>=b.length||a<-b.length?null:0<=a?b[a+1]:b[-(a+1)]}
function sa(a){a[0].isIntersecting?(H().dataset.F=!0,document.getElementById("scroll-down-container").setAttribute("hidden",!0)):(delete H().dataset.F,0<H().querySelectorAll(".message").length&&document.getElementById("scroll-down-container").removeAttribute("hidden"))}function I(){return document.getElementById("outer-container")}function J(){return document.getElementById("promo")}function K(){return document.getElementById("error-container")}
function L(){return document.getElementById("intro-container")}function H(){return document.getElementById("messages")}function M(){return document.getElementById("last-message")}function N(){return document.getElementById("message")}function ta(){return document.getElementById("user-name")}function ua(){return document.getElementById("messages-card-container")}function va(){return document.getElementById("youtube-stream-container")}function O(){return document.getElementById("youtube-video")}
function P(){return document.getElementById("youtube-chat")}function wa(){return document.getElementById("hidden-audio")};function Q(a,b,c,e,h,l){this.text=a;this.f=b;this.c=c;this.H=e;this.b=h;this.a=void 0===l?1:l;Date.now()}function xa(a){a.b()&&a.b().removeAttribute("disabled")}function ya(a){return"\ud83d\udc4f"===a.text||"\ud83d\udc4e"===a.text?a.text.repeat(R(3,6)):a.text+"!".repeat(R(1,3))+"1".repeat(R(0,2))+"!".repeat(R(1,2))}function za(a){return"\ud83d\udc4f"===a.text||"\ud83d\udc4e"===a.text?a.text:a.text+"!!"}function S(a){return"\ud83d\udc4f"===a.text?"APPLAUSE":"\ud83d\udc4e"===a.text?"BOO":a.text}
function R(a,b){return a+Math.floor(Math.random()*(b-a+1))}
var T=[new Q("SCIENCE","\ud83d\udd2c","science1.mp4 science2.mp4 science3.mp4 science4.mp4 science5.mp4 science6.mp4 science7.mp4".split(" "),function(){return document.getElementById("science-form")},function(){return document.getElementById("science")}),new Q("ART","\ud83c\udfa8",["art1.mp4","art2.mp4","art3.mp4"],function(){return document.getElementById("art-form")},function(){return document.getElementById("art")}),new Q("MAPS","\ud83d\uddfa\ufe0f",["maps1.mp4","maps2.mp4","maps3.mp4"],function(){return document.getElementById("maps-form")},
function(){return document.getElementById("maps")}),new Q("SHIPS","\ud83d\udea2","ships1.mp4 ships2.mp4 ships3.mp4 ships4.mp4 ships5.mp4 ships6.mp4".split(" "),function(){return document.getElementById("ships-form")},function(){return document.getElementById("ships")}),new Q("\ud83d\udc4f","\ud83d\udc4f",["applause1.mp4","applause2.mp4","applause3.mp4"],function(){return document.getElementById("applause-form")},function(){return document.getElementById("applause")},2),new Q("\ud83d\udc4e","\ud83d\udc4e",
["boo1.mp4","boo2.mp4","boo3.mp4"],function(){return document.getElementById("boo-form")},function(){return document.getElementById("boo")}),new Q("STEEN","\ud83c\udf99\ufe0f",["steen1.mp4","steen2.mp4","steen3.mp4"],function(){return document.getElementById("steen-form")},function(){return document.getElementById("steen")})];function U(a,b){window.firebase.analytics instanceof Function&&window.firebase.analytics().logEvent(a,b)};function Aa(){var a,b;C(function(c){if(1==c.a)return c.f=2,y(c,window.firebase.messaging().getToken(),4);if(2!=c.a)return(a=c.j)?window.firebase.firestore().collection("fcmTokens").doc(a).set({uid:window.firebase.auth().currentUser.uid,timestamp:window.firebase.firestore.FieldValue.serverTimestamp()}):Ba(),ca(c);b=da(c);console.error("Unable to get messaging token.",b);c.a=0})}
function Ca(){var a,b;C(function(c){if(1==c.a)return c.f=2,y(c,window.firebase.messaging().getToken(),4);if(2!=c.a)return(a=c.j)&&window.firebase.firestore().collection("fcmTokens").doc(a).delete().catch(function(e){console.error("Error removing token: ",e)}),ca(c);b=da(c);console.error("Unable to get messaging token.",b);c.a=0})}function Ba(){Notification.requestPermission().then(function(){Aa()}).catch(function(a){console.error("Unable to get permission to notify.",a)})};function Da(a,b){this.ref=a;this.b=b;this.a=null;var c=this;a.onDisconnect().remove().then(function(){c.a=a.set(!0);c.a.catch(b)},b)}Da.prototype.end=function(){if(this.a){var a=this;return this.a.then(function(){return a.ref.remove().then(function(){a.a=null;return a.end()},a.b)},function(){})}return this.ref.onDisconnect().cancel().catch(this.b)};
function V(){var a=window.firebase.auth(),b=window.firebase.database().ref("_firebase_extensions/presence"),c=this;this.ref=b;this.c=!1;this.a=this.user=null;this.f=!0;var e=this;b.root.child(".info/connected").on("value",function(h){e.c=h.val();e.a&&!e.c&&(e.a.end(),e.a=null);e.b()});a.onAuthStateChanged(function(h){!c.a||h&&h.uid===c.user.uid||(c.a=null);c.user=h;c.b()})}function Ea(){var a=Fa();a.f=!1;a.b();Promise.resolve()}
function Ga(){var a=Fa();a.f=!0;if(a.a){var b=a.a.end();a.a=null;return b}return Promise.resolve()}V.prototype.b=function(){if(!this.a&&!this.f&&this.c&&this.user){var a="";for(var b=0;20>b;b++)a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));a=this.ref.child(this.user.uid).child("sessions").child(a);this.a=new Da(a,this.g)}};
V.prototype.g=function(a){console.error("Error updating presence",a);this.a.end();this.a=null;"PERMISSION_DENIED"!==a.code&&setTimeout(this.b,1E3)};var Ha=null;function Fa(){Ha instanceof V||(Ha=new V);return Ha};function W(){return window.firebase.auth().currentUser.uid}function Ia(){return window.firebase.auth().currentUser.photoURL||"/images/profile_placeholder.png"};function Ja(){document.getElementById("message-form")&&document.getElementById("message-form").addEventListener("submit",Ka);document.getElementById("sign-out").addEventListener("click",La);document.getElementById("sign-in").addEventListener("click",Ma);document.getElementById("sign-in-splash").addEventListener("click",Ma);document.getElementById("notifications-switch")&&document.getElementById("notifications-switch").addEventListener("click",function(c){c.target.checked?Aa():Ca()});for(var a=n(T),
b=a.next();!b.done;b=a.next())b=b.value,b.H()&&b.H().addEventListener("submit",ka(Na,b));N()&&(N().addEventListener("keyup",Oa),N().addEventListener("change",Oa));M()&&((new window.IntersectionObserver(sa,{root:H(),rootMargin:"0px",threshold:.1})).observe(M()),document.getElementById("scroll-down-form")&&document.getElementById("scroll-down-form").addEventListener("submit",function(c){c.preventDefault();M().scrollIntoView(!1)}))}
function Ma(){var a=new firebase.auth.GoogleAuthProvider;firebase.auth().signInWithPopup(a);U("login",{method:""})}function La(){Ga().then(function(){return firebase.auth().signOut()})}function Pa(a){T.forEach(function(b){a===za(b)&&window.firebase.firestore().collection(S(b)).doc(W()).set({profilePicUrl:Ia(),timestamp:window.firebase.firestore.FieldValue.serverTimestamp()}).catch(function(c){console.error("Error writing new message to database",c)})})}
function Qa(a){Pa(a);return window.firebase.firestore().collection("messages").add({uid:W(),name:window.firebase.auth().currentUser.displayName,text:a,profilePicUrl:Ia(),timestamp:window.firebase.firestore.FieldValue.serverTimestamp()}).catch(function(b){console.error("Error writing new message to database",b)})}function Ka(a){return C(function(b){a.preventDefault();U("share",{method:"chat",content_type:"freeform",content_id:""});return y(b,Ra(N().value),0)})}
function Na(a,b){return C(function(c){if(1==c.a)return b.preventDefault(),U("share",{method:"chat",content_type:S(a),content_id:""}),y(c,Ra(za(a)),2);a.b().setAttribute("disabled","true");setTimeout(function(){return xa(a)},1E3);c.a=0})}
function Ra(a){return C(function(b){if(1==b.a){var c;if(c=a)window.firebase.auth().currentUser?c=!0:(document.getElementById("must-signin-snackbar").MaterialSnackbar.showSnackbar({message:"You must sign-in first",timeout:2E3}),c=!1);c?b=y(b,Qa(a),3):(b.a=0,b=void 0);return b}c=N();c.value="";c.parentNode.MaterialTextfield&&c.parentNode.MaterialTextfield.boundUpdateClassesHandler();Oa();b.a=0})}
function Oa(){N().value?document.getElementById("submit").removeAttribute("disabled"):document.getElementById("submit").setAttribute("disabled","true")};var Sa=T.map(function(a){return za(a)});function Ta(a,b,c,e,h,l,f){this.id=a;this.timestamp=b;this.f=c;this.c=e;this.a=h;this.text=l;this.b=f;this.g=new Autolinker({N:!0,O:!1,P:!1})}Ta.prototype.remove=function(){var a=document.getElementById(this.id);a&&a.parentNode.removeChild(a)};
function Ua(a){if(!Sa.includes(a.text)){var b=ra(Va(a)),c=H().dataset.F||null===b&&a.f===W(),e=document.getElementById(a.id)||Wa(a,b);a.a&&(e.querySelector(".pic").style.backgroundImage="url("+qa(a.a)+")");e.querySelector(".name").textContent=a.c;a.timestamp&&1E4<a.timestamp.getTime()&&(e.querySelector(".timestamp").textContent=a.timestamp.toLocaleDateString()+" "+a.timestamp.toLocaleTimeString());b=e.querySelector(".message");if(G.g.includes(W())&&!a.id.startsWith("callback-message-")&&!e.querySelector(".admin")){var h=
document.createElement("a");h.className="admin";h.setAttribute("href","#");h.textContent="delete";h.addEventListener("click",function(){firebase.firestore().collection("messages").doc(a.id).delete().catch(function(d){console.error("Error removing message: ",d)})});var l=e.querySelector(".byline");l.insertBefore(h,l.childNodes[0])}if(a.text)b.textContent=a.text,b.innerHTML=DOMPurify.sanitize(b.innerHTML),b.innerHTML=a.g.link(b.innerHTML),b.innerHTML=b.innerHTML.replace(/\n/g,"<br>");else if(a.b){h=
document.createElement("video");h.a=!0;h.autoplay=!0;h.muted=!0;h.className="callback-video";l=document.createElement("source");l.src=a.b;l.type="video/mp4";var f=document.createTextNode("Your browser does not support the video tag.");h.innerHTML="";h.appendChild(l);h.appendChild(f);h.onloadedmetadata=function(){c&&M().scrollIntoView(!1)};b.innerHTML="";b.appendChild(h)}setTimeout(function(){e.classList.add("visible")},1);c&&M().scrollIntoView(!1);N()&&N().focus()}}
function Wa(a,b){var c=document.createElement("div");c.innerHTML='<div class="message-container"><div class="spacing"><div class="pic"></div></div><div class="message"></div><div class="byline"><div class="timestamp"></div><div class="name"></div></div></div>';c=c.firstChild;c.setAttribute("id",a.id);c.setAttribute("timestamp",Va(a));b||(b=M());H().insertBefore(c,b);return c}function Va(a){a.timestamp||(a.timestamp=new Date);return a.timestamp.getTime()}var Xa=new Map,Z=[];
function Ya(a){a.docChanges&&(a.docChanges().forEach(function(b){if("removed"===b.type)Xa.get(b.doc.id).remove();else{var c=b.doc.data(),e=c.timestamp?c.timestamp.toDate():null;b=b.doc.id;c=new Ta(b,e,c.uid,c.name,c.profilePicUrl,c.text,c.videoUrl);Xa.set(b,c);Ua(c)}}),a.empty||Z.push(a.query.startAfter(a.docs[a.size-1]).onSnapshot(Ya,Za)))}function Za(a){console.error("Error querying Firestore: ",a)}function $a(){for(var a=n(Z),b=a.next();!b.done;b=a.next())b=b.value,b();Z=[]};function ab(a){this.i=a;this.b=Date.now()-F(this.i.a);this.a=this.u=null}function bb(a){a.i.c.forEach(function(b){var c=document.createElement("audio");c.id=b;c.b=!0;c.hidden=!0;c.preload="auto";c.src="video/"+b;wa().appendChild(c)})}
function cb(a,b){if(b){var c=Math.max(a.b,Date.now()-F(a.i.a)),e=b.filter(function(h){return db(h.data())>c});0<e.length&&(b=db(b[0].data()),0<b&&(e.length>=la(a.i.a)?(a.a&&(a.a.a.remove(),a.a=null),a.b=b+1E3,eb(a,b+1),U("screen_view",{screen_name:S(a.i)})):(e=e.map(function(h){return{uid:h.id,K:h.data().profilePicUrl}}),fb(a,b,e,c))))}}
function fb(a,b,c,e){if(!a.a||a.a.timestamp<e)a.a=new gb(a.i.f,ya(a.i),b,a.i.a),hb(a.a);b=n(c);for(c=b.next();!c.done;c=b.next()){var h=c.value;c=a.a;e=h.uid;h=h.K;if(!c.c.includes(e)){c.c.push(e);var l=c.a.querySelector(".callback-progress-bar");l.style.width=100*c.c.length/la(c.b)+"%";var f=document.createElement("div");f.className="callback-progress-voice";h&&(f.style.backgroundImage="url("+qa(h)+")");l.insertBefore(f,c.a.querySelector(".callback-progress-callback"));(H().dataset.F||e===W())&&
M().scrollIntoView(!1)}}}function eb(a,b){var c=a.i.c[Math.floor(Math.random()*a.i.c.length)],e=ib.next();b=new Date(b);a=ya(a.i);a=new Ta(e,b,"",a,"images/adventureharvey.jpg","","video/"+c);Xa.set(e,a);Ua(a);document.getElementById(c).play()}var ib=new pa;function gb(a,b,c,e){this.id=ib.next();this.f=a;this.g=b;this.timestamp=c;this.b=e;this.a=null;this.c=[]}
function hb(a){if(!document.getElementById(a.id)){var b=document.createElement("div");b.innerHTML='<div class="message-container">  <div class="spacing"><div class="callback-emoji"></div></div>  <div class="callback-progress">    <div class="callback-progress-bar">      <div class="callback-progress-callback"></div>    </div>  </div></div>';a.a=b.firstChild;a.a.setAttribute("id",a.id);a.a.setAttribute("timestamp",a.timestamp);a.a.querySelector(".callback-emoji").innerText=a.f;a.a.querySelector(".callback-progress-callback").innerText=
a.g;(b=ra(a.timestamp))||(b=M());H().insertBefore(a.a,b);setTimeout(function(){a.a.classList.add("visible")},1);setTimeout(function(){var c=a.a.querySelector(".callback-progress-bar");c.style.transition="opacity "+(F(a.b)-1E3)+"ms ease-in";c.style.opacity=0},1001);setTimeout(function(){var c=a.a.querySelector(".callback-progress-bar");c.classList.remove("callback-progress-bar");c.classList.add("callback-progress-bar-expired");c.removeAttribute("style")},F(a.b))}H().dataset.F&&M().scrollIntoView(!1)}
function db(a){return a&&a.timestamp&&a.timestamp.toMillis?a.timestamp.toMillis():-1}var jb=T.map(function(a){return new ab(a)});function kb(a){a.m?a.f&&document.getElementById("error-link")?(K().removeAttribute("hidden"),I().setAttribute("hidden",!0),J().setAttribute("hidden",!0),document.getElementById("error-link").setAttribute("href",a.f),U("screen_view",{screen_name:"error"})):(I().hasAttribute("hidden")&&(I().removeAttribute("hidden"),J()&&J().setAttribute("hidden",!0),K()&&K().setAttribute("hidden",!0),U("screen_view",{screen_name:"main"})),O()&&(a.b?(O().src="https://www.youtube.com/embed/"+a.b,O().removeAttribute("hidden")):
O().setAttribute("hidden",!0)),P()&&(a.a?(P().src="https://www.youtube.com/live_chat?v="+a.a+("&embed_domain="+window.location.hostname),P().removeAttribute("hidden")):P().setAttribute("hidden",!0)),va()&&(a.b||a.a?va().removeAttribute("hidden"):va().setAttribute("hidden",!0)),lb()):J()&&(J().removeAttribute("hidden"),I().setAttribute("hidden",!0),K().setAttribute("hidden",!0),U("screen_view",{screen_name:"promo"}))}
function mb(a){var b,c,e,h,l;return C(function(f){if(1==f.a){if(!a){ta().setAttribute("hidden","true");document.getElementById("user-pic").setAttribute("hidden","true");document.getElementById("kebab-menu").setAttribute("hidden","true");document.getElementById("sign-in").removeAttribute("hidden");document.getElementById("signin-splashscreen").removeAttribute("hidden");ua().setAttribute("hidden","true");b=n(jb);for(c=b.next();!c.done;c=b.next())e=c.value,e.u&&(e.u(),e.u=null);$a();f.a=0;return}Ea();
h=Ia();l=window.firebase.auth().currentUser.displayName;document.getElementById("user-pic").style.backgroundImage="url("+qa(h)+")";ta().textContent=l;ta().removeAttribute("hidden");document.getElementById("user-pic").removeAttribute("hidden");document.getElementById("kebab-menu").removeAttribute("hidden");document.getElementById("sign-in").setAttribute("hidden","true");document.getElementById("signin-splashscreen").setAttribute("hidden","true");Aa();wa().innerHTML="";jb.forEach(function(d){return bb(d)});
kb(G);if(G.D||!L()){nb();f.a=0;return}return y(f,ob(),4)}nb();f.a=0})}function nb(){ua().removeAttribute("hidden");L()&&L().setAttribute("hidden",!0);N()&&(N().removeAttribute("disabled"),N().focus());var a=G.v,b=firebase.firestore().collection("messages").limit(12);a&&(b=b.where("timestamp",">",a));b=b.orderBy("timestamp","desc");0==Z.length&&Z.push(b.onSnapshot(Ya,Za));U("screen_view",{screen_name:"chat"})}
function ob(){L().removeAttribute("hidden");ua().setAttribute("hidden",!0);U("screen_view",{screen_name:"introduction"});return new Promise(function(a){document.getElementById("intro-button").addEventListener("click",function(){wa().querySelectorAll("audio").forEach(function(b){b.volume=0;b.muted=!0;b.playbackRate=2;b.onended=function(){b.volume=1;b.muted=!1;b.playbackRate=1;b.onended=null};b.play()});T.forEach(function(b){return xa(b)});G.D=!0;a()})})}
function lb(){for(var a={},b=n(jb),c=b.next();!c.done;a={s:a.s},c=b.next())a.s=c.value,a.s.u&&a.s.u(),c=window.firebase.firestore().collection(S(a.s.i)).orderBy("timestamp","desc").limit(la()),a.s.u=c.onSnapshot(function(e){return function(h){cb(e.s,h.docs)}}(a),function(e){console.error("Error querying Firestore: ",e)})};window.firebase&&firebase.app instanceof Function&&firebase.app().options?(firebase.performance(),firebase.analytics(),Ja(),Fa(),firebase.auth().onAuthStateChanged(mb),G.l.push(kb),ma()):window.alert("You have not configured and imported the Firebase SDK. Make sure you go through the codelab setup instructions and make sure you are running the codelab using `firebase serve`");
